import Foundation

enum Constants {
    enum Panel {
        static let width: CGFloat = 400
        static let verticalHeight: CGFloat = 420
        static let horizontalHeight: CGFloat = 220
        static let searchBarHeight: CGFloat = 40
    }

    enum History {
        static let defaultMax = 500
        static let absoluteMax = 5000
        static let options = [50, 100, 200, 500, 750, 1000, 1500]
        static let previewCharacterLimit = 512
        static let thumbnailEdge: CGFloat = 64
        static let largePayloadBytes = 512 * 1024
        static let largePayloadDigestSampleBytes = 64 * 1024
    }

    enum Pasteboard {
        static let alwaysRejectIfPresent: Set<String> = [
            "com.agilebits.onepassword",
            "org.nspasteboard.ConcealedType",
        ]
        static let denylistedTypes: Set<String> = [
            "org.nspasteboard.TransientType",
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.AutoGeneratedType",
            "com.agilebits.onepassword",
            "com.typeit4me.clipping",
            "de.petermaurer.TransientPasteboardType",
            "Pasteboard generator type",
            "net.antelle.keeweb",
        ]
        static let maxTypesPerItem = 32
        /// Consecutive snapshot retries allowed before spacing them out while the
        /// writing app is still filling the pasteboard.
        static let monitorSnapshotBurst = 3
        static let monitorSnapshotBackoffBaseMilliseconds = 25
        static let monitorSnapshotBackoffCapMilliseconds = 250
    }

    enum UI {
        static let windowCornerRadius: CGFloat = 16
        static let cardCornerRadius: CGFloat = 12
        static let glassOpacity: Double = 0.4
        static let glassBorderWidth: CGFloat = 0.5
    }
}
